OUTPUT=../output/
all:
	g++ -DTEST_6P2 -DTEST_5P5P1 cpp_primer.cpp
test:
	g++ -DTEST_10P3P2 cpp_primer.cpp -o $(OUTPUT)/test_10.3.2
test6.2:
	g++ -DTEST_6P2 cpp_primer.cpp -o $(OUTPUT)/test_6.2
test10.3.2:
	g++ -DTEST_10P3P2 cpp_primer.cpp -o $(OUTPUT)/test_10.3.2
clean:
	rm -f a.out
